Library application ES6
blackpintz/Library pull request #2
Opened 2020-09-09 14:29 UTC by 8Bts

In this branch, we built the main part of the application. It includes:
- The homepage that shows the list of books in cards.
- The button that displays a form for adding a new book.
- The button that toggles the `read` status of the book.
We used DOM manipulation in most parts of the application and all DOM manipulation statements are living in the `dom.js` file.

2020-09-09 19:08 UTC, uryelah requested changes
Hi **Rose Wanjohi & Rashid Mammadli**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with this project and especially for managing multiple files and setting up a localStore db!
There are some issues to fix but they will be pretty fast fixes for you from the complexity and quality of your code.

# Required Changes 🏗️ 🐛 💡

(Check the comments below too)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-09-09 19:08 UTC, uryelah commented on README.md
> +## Live Demo
- [ ] Add a section about how to run your project locally too since you have a specific setup and dependencies.

2020-09-09 19:08 UTC, uryelah commented on README.md
> +## Desktop
- [ ] [OPTIONAL] It's usually better to put the screenshot at the top are of your readme, near the title or about. That makes the reader, or recruiter, more interested.

2020-09-09 19:08 UTC, uryelah commented on assets/dom.js
> +function displayBooks(bookArr) {
- [ ] The project description at Odin project recommends you to name this function `render`. Let's rename it so it's function is clearer/uses the common jargon for Javascript and it's frameworks.
![render_requirement](https://user-images.githubusercontent.com/16193212/92642167-3081bd00-f2b6-11ea-9b8e-d379b1330c28.png)

2020-09-10 09:34 UTC, rOluochKe approved these changes
Hello @8Bts and @blackpintz 
### Well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy hacking!

### [Optional]
- Remove the comments in your codebase

2020-09-10 10:58 UTC, merged